Update GitHub Actions workflow to check broken links
wir wollen dass es failed wenn es zu irgendeiner ausgabe kommt

diff --git a/.github/workflows/scan-links.yml b/.github/workflows/scan-links.yml
--- a/.github/workflows/scan-links.yml
+++ b/.github/workflows/scan-links.yml
@@ -10,5 +10,11 @@ jobs:
     name: Check with linkinator
     runs-on: ubuntu-latest
     steps:
+      - name: linkinator
+        id: linkinator
       # status: 0 means that we have been blocked by their firewall/cloudflare etc
-      - run: npx linkinator --format=json --redirects=error https://bringbackourneighbours.de/internal-check-links/ |  jq '.links[] | select(.state =="BROKEN" and .status != 0)'
+        run: | echo "brokenlinks=$(npx linkinator --format=json --redirects=error https://bringbackourneighbours.de/internal-check-links/ |  jq '.links[] | select(.state =="BROKEN" and .status != 0)') >> $GITHUB_OUTPUT
+      - name: outcheck
+        id: check
+        if: {{steps.linkinator.outputs.brokenlinks != ''}}
+        run: | exit 1
