Fix linkinator output handling in workflow

diff --git a/.github/workflows/scan-links.yml b/.github/workflows/scan-links.yml
--- a/.github/workflows/scan-links.yml
+++ b/.github/workflows/scan-links.yml
@@ -13,8 +13,8 @@ jobs:
       - name: linkinator
         id: linkinator
       # status: 0 means that we have been blocked by their firewall/cloudflare etc
-        run: | npx linkinator --format=json --redirects=error https://bringbackourneighbours.de/internal-check-links/ |  jq '.links[] | select(.state =="BROKEN" and .status != 0)') >> $GITHUB_OUTPUT
+        run: echo "brokenlinks=$(npx linkinator --format=json --redirects=error https://bringbackourneighbours.de/internal-check-links/ |  jq '.links[] | select(.state =="BROKEN" and .status != 0)')" >> $GITHUB_OUTPUT
       - name: outcheck
         id: check
-        if: {{steps.linkinator.outputs.brokenlinks != ''}}
-        run: | exit 1
+        if: ${{steps.linkinator.outputs.brokenlinks != ''}}
+        run: exit 1
